### PR TITLE
Escape text for XML compatibility, add flow, format code, upgrade code

### PR DESCRIPTION
**Pull request by mdeweerd**
Fixed issue when the input contains characters such as '<>' that were interpreted as XML (SVG) tags.

At the same time, added flow that formats and checks the code.

### CODE REVIEW

**Comment by markrages** [comment]
The formatting really mangles the code, especially the RGB tables.

Can you make a clean commit with just the bugfix please?

**Comment by mdeweerd** [comment]
You'ld need 

https://github.com/markrages/ansi_svg/blob/7999351f8a9cbf05b943b6f3808e89627b522e97/ansi_svg.py#L5

and

https://github.com/markrages/ansi_svg/blob/7999351f8a9cbf05b943b6f3808e89627b522e97/ansi_svg.py#L123

The formating of the code applies the nowadays common black and flake8 formatting tools which is setup in the pre-commit configuration.

**Comment by markrages** [comment]
Thanks, I will merge that fix.

Code is written for people to read, so if the tools make the code harder to read, they make it worse.  I like Hettinger's talk about PEP8: https://www.youtube.com/watch?v=wf-BqAjZb8M

**Comment by markrages** [comment]
Merged in 7d043a60cee19ba1505ce97db181841edd2c861d

Thank you!

**Comment by mdeweerd** [comment]
My approach is, if the tool makes it hard to read, think about writing it differently.

Having uniformly formatted code helps focus on the code, and limits the discussion on how to format it. 

In this case, the constants could be renamed to all have equal size, and as they are constants I'ld write them uppercase.
They could be BRGT__ON, BRGT_OFF, NORM__ON, NORM_OFF, NULL_CLR and formatting problem solved.

Anyway, it's just a quick script you shared, and I ported my setup to see if there was a limitation that the tools could help find to explain why the output was not ok.

**Pull request closed without merging**
